import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  //please short from a to z or by categori if adding styles

  //Single Styles
  alItCenter: { alignItems: 'center' },
  br0: { borderRadius: 0 },
  br10: { borderRadius: 10 },
  br15: { borderRadius: 15 },
  column: { flexDirection: 'column' },
  fx1: { flex: 1 },
  fx3: { flex: 3 },
  fx4: { flex: 4 },
  fxg1: { flexGrow: 1 },
  jcSpcBtw: { justifyContent: 'space-between' },
  jcSpcFxend: { justifyContent: 'flex-end' },
  mr8: { margin: 8 },
  mr12: { margin: 12 },
  mr16: { margin: 16 },
  mrb4: { marginBottom: 4 },
  mrb8: { marginBottom: 8 },
  mrb12: { marginBottom: 12 },
  mrb16: { marginBottom: 16 },
  mrb20: { marginBottom: 20 },
  mrb24: { marginBottom: 24 },
  mrb36: { marginBottom: 36 },
  mrh8: { marginHorizontal: 8 },
  mrh12: { marginHorizontal: 12 },
  mrh16: { marginHorizontal: 16 },
  mrl4: { marginLeft: 4 },
  mrl8: { marginLeft: 8 },
  mrl12: { marginLeft: 12 },
  mrl16: { marginLeft: 16 },
  mrr8: { marginRight: 8 },
  mrr12: { marginRight: 12 },
  mrr16: { marginRight: 16 },
  mrt4: { marginTop: 4 },
  mrt12: { marginTop: 12 },
  mrt16: { marginTop: 16 },
  mrv8: { marginVertical: 8 },
  mrv16: { marginVertical: 16 },
  pd0: { padding: 0 },
  pd12: { padding: 12 },
  pd16: { padding: 16 },
  pd20: { padding: 20 },
  pdh8: { paddingHorizontal: 8 },
  pdh12: { paddingHorizontal: 12 },
  pdh16: { paddingHorizontal: 16 },
  pdv8: { paddingVertical: 8 },
  pdv16: { paddingVertical: 16 },
  row: { flexDirection: 'row' },
  txtAlCtr: { textAlign: 'center' },
  txtCapitalize: { textTransform: 'capitalize' },
  txtDecLineT: { textDecorationLine: 'line-through' },
  txtUppercase: { textTransform: 'uppercase' },
  w100: { width: '100%' },

  //Custom Styles
  rowAlgCenter: { flexDirection: 'row', alignItems: 'center' },
});

export default styles;
